map_update_interval: 2.0         # 지도 갱신 시간 간격(sec) default = 2.0
maxUrange: 6.0                   # 사용하고자 하는 레이저 센싱 최대 범위(meter) default = 4.0
maxRange : 8.0                   # 라이다 센서의 최대 범위
sigma: 0.05                      # 레이저 대응 탐색의 표준 편차 default = 0.05
kernelSize: 1                    # 레이저 대응 탐색의 윈도우 사이즈 default = 1
lstep: 0.05                      # 초기 탐색 스텝(이동) default = 0.05
astep: 0.05                      # 초기 탐색 스텝(회전) default = 0.05
iterations: 5                    # 스캔매칭 반복 수 default = 5
lsigma: 0.075                    # 빔 우도계산의 표준 편차 default = 0.075
ogain: 3.0                       # 우도 평골화 게인 default = 3
lskip: 0                         # 각 스캔에서 건너뛸 빔의 개수 default = 0
minimumScore: 50                 # 스캔 매칭의 결과를 고려한 최소 점수 default = 50
srr: 0.1                         # 오도메트리 에러(이동 -> 이동) default = 0.1
srt: 0.2                         # 오도메트리 에러(이동 -> 회전) default = 0.2
str: 0.1                         # 오도메트리 에러(회전 -> 이동) default = 0.1 
stt: 0.2                         # 오도메트리 에러(회전 -> 회전) default = 0.2
linearUpdate: 1.0                # 처리에 필요한 최저 이동 거리 default = 1
angularUpdate: 0.2               # 처리에 필요한 최저 회전 각도 default = 0.2
temporalUpdate: 0.5              # 마지막으로 스캔한 시간이 이 갱신 시간을 넘었을 경우, 스캔을 한다 default = 0.5
resampleThreshold: 0.5           # 리샘플 한계치 값 default = 0.5
particles: 100                   # 파티클 필터의 파티클 수 default = 100
xmin: -10.0                      # 초기 맵 사이즈(최소 x) default = -10 
ymin: -10.0                      # 초기 맵 사이즈(최소 y) default = -10
xmax: 10.0                       # 초기 맵 사이즈(최대 x) default = 10
ymax: 10.0                       # 초기 맵 사이즈(최대 y) default = 10
delta: 0.05                      # 지도의 해상도(거리/픽셀) default = 0.05
llsamplerange: 0.01              # 우도계산의 범위(이동) default = 0.01
llsamplestep: 0.01               # 우도계산의 스텝폭(이동) default = 0.01
lasamplerange: 0.005             # 우도계산의 범위(회전) default = 0.005
lasamplestep: 0.005              # 우도계산의 스텝폭(회전) default = 0.005
